* Literature

* 1

Laiho et.al. 2015
High-Dimensional Computing with Sparse Vectors
https://www.researchgate.net/publication/299535938_High-Dimensional_Computing_with_Sparse_Vectors


* 2

Schlegel et.al. 2021  A comparison of Vector Symbolic Architectures

http://www.arxiv.org/abs/2001.11797
arXiv:2001.11797

* 3

Pentti Kanerva. Hyperdimensional computing: An introduction to computing in distributed representation with
high-dimensional random vectors. Cognitive Computation, 1(2):139–159, 2009. doi:10.1007/s12559-009-9009-8.

* 4

Zhonghao Yang 2023
Cognitive modeling and learning with sparse binary hypervectors

https://paperswithcode.com/paper/cognitive-modeling-and-learning-with-sparse#code

* 5

Pentti Kanerva 1993 Sparse Distributed Memory and Related Models

* 6

Pentti Kanerva /Sparse Distributed Memory/, 1988

* 7

Vector Symbolic Architectures as a Computing Framework for Emerging Hardware
Denis Kleyko, Mike Davies, E. Paxon Frady, Pentti Kanerva, Spencer J. Kent, Bruno A. Olshausen, Evgeny Osipov, Jan M. Rabaey, Dmitri A. Rachkovskij, Abbas Rahimi, Friedrich T. Sommer

https://arxiv.org/abs/2106.05268
